### PR TITLE
Clean up the code-base

### LINKED ISSUE #18: Clean up initial code base

### PR DESCRIPTION
**Pull request by helloworld12321**
Remove references to users, todos, and anything else left over from the labs.

### CODE REVIEW

**Comment by helloworld12321** [comment]
I vote that we keep `MongoSpec.java`. Because it's just a self-contained check that we can connect to the database, it works just as well for our project as it worked for the labs. (It doesn't make any references to `User` or `UserController` or anything, and it only messes with the database named `test`, not the actual `dev` database that we're using for our real work.)

**Comment by helloworld12321** [comment]
I don't really know where to put pull requests in ZenHub :) I think I'll just leave it in new-issues.

**Comment by helloworld12321** [comment]
I would recommend that, once we start working on features, we change the home page into something more meaningful. (For example, maybe we could ditch the homepage entirely and just send Prof. Rachel straight to the all-of-my-notes page.)

For now, though, I'm leaving the home page in, just as filler 🙃.

**Comment by helloworld12321** [comment]
Oops, looks like `mongoseed.sh` isn't happy.

**Comment by helloworld12321** [comment]
Closes #18.

**Review by ErikRauer — APPROVED** [review]
Looks good to me

**Pull request merged**
